'org.logicware.pdb.DatabaseClass'('org.logicware.domain.geometry.Point','',false,'Point',false,'org.logicware.domain.geometry.Point','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(3,['org.logicware.pdb.prolog.PrologHashMap$HashEntry'(x,'org.logicware.pdb.DatabaseField'(x,'',1,double,false,'org.logicware.domain.geometry.Point.x',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(y,'org.logicware.pdb.DatabaseField'(y,'',2,double,false,'org.logicware.domain.geometry.Point.y',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(idp,'org.logicware.pdb.DatabaseField'(idp,'',0,'java.lang.String',false,'org.logicware.domain.geometry.Point.idp',false,false,nil,nil,nil,nil,nil))])).

'org.logicware.pdb.DatabaseClass'('org.logicware.domain.geometry.Segment','',false,'Segment',false,'org.logicware.domain.geometry.Segment','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(3,[nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(point1,'org.logicware.pdb.DatabaseField'(point1,'',2,'org.logicware.domain.geometry.Point',false,'org.logicware.domain.geometry.Segment.point1',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(point0,'org.logicware.pdb.DatabaseField'(point0,'',1,'org.logicware.domain.geometry.Point',false,'org.logicware.domain.geometry.Segment.point0',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(ids,'org.logicware.pdb.DatabaseField'(ids,'',0,'java.lang.String',false,'org.logicware.domain.geometry.Segment.ids',false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.logicware.pdb.DatabaseClass'('org.logicware.domain.geometry.Polygon','',false,'Polygon',false,'org.logicware.domain.geometry.Polygon','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(4,[nil,nil,nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(id,'org.logicware.pdb.DatabaseField'(id,'',0,'java.lang.String',false,'org.logicware.domain.geometry.Polygon.id',false,false,nil,nil,nil,nil,nil)),nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(segment0,'org.logicware.pdb.DatabaseField'(segment0,'',1,'org.logicware.domain.geometry.Segment',false,'org.logicware.domain.geometry.Polygon.segment0',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(segment1,'org.logicware.pdb.DatabaseField'(segment1,'',2,'org.logicware.domain.geometry.Segment',false,'org.logicware.domain.geometry.Polygon.segment1',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(segment2,'org.logicware.pdb.DatabaseField'(segment2,'',3,'org.logicware.domain.geometry.Segment',false,'org.logicware.domain.geometry.Polygon.segment2',false,false,nil,nil,nil,nil,nil))])).

'org.logicware.pdb.DatabaseClass'('org.logicware.domain.geometry.Tetragon','',false,'Tetragon',false,'org.logicware.domain.geometry.Tetragon','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(1,['org.logicware.pdb.prolog.PrologHashMap$HashEntry'(segment3,'org.logicware.pdb.DatabaseField'(segment3,'',0,'org.logicware.domain.geometry.Segment',false,'org.logicware.domain.geometry.Tetragon.segment3',false,false,nil,nil,nil,nil,nil)),nil])).

'org.logicware.pdb.DatabaseClass'('org.logicware.domain.model.Person','',false,'Person',false,'org.logicware.domain.model.Person','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(12,['org.logicware.pdb.prolog.PrologHashMap$HashEntry'(joinDate,'org.logicware.pdb.DatabaseField'(joinDate,'',9,'java.util.Date',false,'org.logicware.domain.model.Person.joinDate',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(lastLoginDate,'org.logicware.pdb.DatabaseField'(lastLoginDate,'',10,'java.util.Date',false,'org.logicware.domain.model.Person.lastLoginDate',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(loginCount,'org.logicware.pdb.DatabaseField'(loginCount,'',11,int,false,'org.logicware.domain.model.Person.loginCount',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(birthDate,'org.logicware.pdb.DatabaseField'(birthDate,'',8,'java.util.Date',false,'org.logicware.domain.model.Person.birthDate',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(phones,'org.logicware.pdb.DatabaseField'(phones,'',5,'java.util.List',false,'org.logicware.domain.model.Person.phones',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(nickNames,'org.logicware.pdb.DatabaseField'(nickNames,'',7,'java.util.Set',false,'org.logicware.domain.model.Person.nickNames',false,false,nil,nil,nil,nil,nil)),nil,nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(lastName,'org.logicware.pdb.DatabaseField'(lastName,'',3,'java.lang.String',false,'org.logicware.domain.model.Person.lastName',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(middleName,'org.logicware.pdb.DatabaseField'(middleName,'',2,'java.lang.String',false,'org.logicware.domain.model.Person.middleName',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(emails,'org.logicware.pdb.DatabaseField'(emails,'',6,'java.util.Collection',false,'org.logicware.domain.model.Person.emails',false,false,nil,nil,nil,nil,nil)),nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(firstName,'org.logicware.pdb.DatabaseField'(firstName,'',1,'java.lang.String',false,'org.logicware.domain.model.Person.firstName',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(address,'org.logicware.pdb.DatabaseField'(address,'',4,'org.logicware.domain.model.Address',false,'org.logicware.domain.model.Person.address',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(id,'org.logicware.pdb.DatabaseField'(id,'',0,'java.lang.Integer',false,'org.logicware.domain.model.Person.id',false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.logicware.pdb.DatabaseClass'('org.logicware.domain.model.Department','',false,'Department',false,'org.logicware.domain.model.Department','org.logicware.pdb.prolog.PrologArrayList'(0,'[]'),'org.logicware.pdb.prolog.PrologHashMap'(3,[nil,'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(id,'org.logicware.pdb.DatabaseField'(id,'',0,'java.lang.Integer',false,'org.logicware.domain.model.Department.id',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(employeesByCubicle,'org.logicware.pdb.DatabaseField'(employeesByCubicle,'',2,'java.util.Map',false,'org.logicware.domain.model.Department.employeesByCubicle',false,false,nil,nil,nil,nil,nil)),'org.logicware.pdb.prolog.PrologHashMap$HashEntry'(name,'org.logicware.pdb.DatabaseField'(name,'',1,'java.lang.String',false,'org.logicware.domain.model.Department.name',false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.logicware.pdb.DatabaseUser'(sa,'',nil,false,false,nil,nil).

